---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment2
  namespace: prod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx3      
        image: nginx:latest # Updated to the latest version
        ports:
        - containerPort: 80