apiVersion: argoproj.io/v1alpha1 # API version for Argo CD Application CRD
kind: Application               # Declares this resource as an Argo CD Application
metadata:
  name: kong                  # Name of the Argo CD Application
  namespace: argocd              # Namespace where Argo CD is installed (not the app's target namespace)
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Updated finalizer for proper resource cleanup
spec:
  project: default              # Argo CD project this app belongs to (default is the built-in project)
  source:
    repoURL: 'https://charts.bitnami.com/bitnami' # Git repo containing Kubernetes manifests
    targetRevision: 15.4.17
    chart: kong # Helm chart to deploy
    helm:
      version: v3 # Helm version to use 
      passCredentials: false
  destination:
    server: 'https://kubernetes.default.svc' # Kubernetes API server address (default
    namespace: monitoring # Namespace in the target cluster to deploy the app
  syncPolicy:
    automated:                 # Enables automated sync (auto-deploy on changes)
      prune: true              # Delete resources not defined in source repo
      selfHeal: true           # Revert out-of-band changes in the cluster
    syncOptions:               # Additional sync options (see below)
    - CreateNamespace=true    # Do not auto-create the destination namespace (set to true to enable)
    - Validate=true            # Validate manifests with 'kubectl apply --dry-run'
    - PrunePropagationPolicy=Background # Use foreground deletion for pruned resources
    - PruneLast=true           # Prune resources after applying new ones
    - SkipDifferences=true
  values: |
    # Configure Kong to run in DB-less mode (no PostgreSQL required)
    env:
      database: "off"
      declarative_config: "/kong_dbless/kong.yml"
    
    # Disable PostgreSQL dependency
    postgresql:
      enabled: false
    
    # Configure Kong for DB-less mode
    dblessConfig:
      configMap: ""
      config: |
        _format_version: "3.0"
        _transform: true
        services: []
        routes: []
        plugins: []
