apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: metrics-server
    targetRevision: 7.4.10
    helm:
      values: |
        extraArgs:
          - "--kubelet-insecure-tls"
          - "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
          - "--metric-resolution=30s"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true