apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
    targetRevision: 3.12.1
    chart: metrics-server
    helm:
      version: v3
      passCredentials: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=Background
    - PruneLast=true
  values: |
    extraArgs:
      - "--kubelet-insecure-tls"
      - "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
      - "--metric-resolution=15s"
      - "--kubelet-use-node-status-port=true"
