---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1      
        image: nginx:1.29.0-alpine # Updated to the latest version
        ports:
        - containerPort: 80